language: node_js
before_install: npm install -g https://github.com/reasonml/esy.git\#beta-v0.0.2
install: esy install
script: esy build
node_js: '6.9'
os: osx
after_success: bash ./update-binaries.sh
cache:
  yarn: true
  directories:
    - $HOME/.esy
env:
  global:
  - secure: YEW8/UzXMuKdgM24RXk8XOsLkOG1YjnqrdFIMod1LEB0Ain1SubYHWCPJjduT47I5sVmMZ5vuG2Fapbu86dz8dVn/MqZFadsK9UDcYYzsoLtm/3l/PXUBCCbIWamNK1WTkh79z023r8DUURsrjjLPXhnfo6fdE1qmLk/Gm+XcZtRlKiVnZLASbOzVBs211yOU03ZSk64fCZ3Pf6AK4P7K1Zu6cvrxaZezZysb3a41PaYVIvNaZhCFdKYxceJmqnhYFaGRHsq6Ftl+7vzBYaIVY1Ejvsd62s1/F4GX6XkHA+38b86ls163KXxkHAGAKeaA/Ydtd7i4Gh4xHZhtvaN6jG2gGEqFaueDFnIknv5ci8sRHJZlDGESZGuS9RVA25NevbXDEs327W3chVBdUhDXaFMEqGAoCDBINfep0AwQaFzYlZGG5/OULA9i7Oj4b6B7sQylaBtGfZ7rNY4JAxjDOKQaNabZMuk1jBMMnxQB1lGWGUF38VfQPCTGYvMWOKOWwHD3azG4AU6C//kAtOP2Nq38wVwMvEzuKUsvGdrRNt6eaXvl0+5GwlastSWxvJltVOsK9XzVmT1qZtv3MCzkLxG55l2cEINczAbVjf+QkgH4gAafZ6M0VE1r8+d7qxDNhZAmIyFxvG+hEx5lbAO/l0GIWI5l3V579c5WfnmIAM=
  - secure: Jubvproie+bmolC2Q2K2ii6C2Pw1ffZJNmKBNeOwcASEoK5ubq5AJHzD0vObegQJlXlKR1nVGLOoi2N3J83A5a13cKku/c+VDbZnn3JdKGEiChrY0IgitO1QDer5yoz/sg3NW9NkV+7MowLPfZCKYROCxcn7vuBOiBkGkPxYv/MEm42aQIxtWyaDMIjCaSgvG7QXdWqMXYI32pJp/8upY1HCcn0FKccZqBynuEj20Sa4PaR98XWbKeJcMZAJ8pqesVlWT1lWMuyUkHApxuL/4kYjvW66FA5dI7SIR3K3GqYnZZUMCq6kXLD7SUSCgWsakzen9+QCadkVQhPyfm4yIj7AhOhxuwkn2TQVXt5vB9dDebsnEBO3RbtTzxcDVlbm2gr89uZXlB8yn/rJD/Prhda8IiPjAphZWbR6RxUcSMf1D/zsYedrM2/9lzhD8eZQREyey1knPBzfWM9sV1y5+8TxbfRMak1HOWhw/yeZFKSA8cocXa7FDb+017qAzZj8NvoFCb1uJMf2+qvTmHJhgFm8XnVSDJuOXtoP7ICIKQXAq+flF3wLGQVAmrds9DVqT2pj2qAqC2HAwXdf0v0fEGJ6uNQ2r1EMxAZhs1gTo2fIqdzxinWO549YBz0pS3DVTiU3PBR4whIZXFtnJlxCowbzHVEv4FwY78TOhmE5Li4=
